name: Trigger auto deployment for ca-chatagent-srv

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: [main]
    paths:
      - "**"
      - ".github/workflows/ca-chatagent-srv-AutoDeployTrigger-2dd86107-b33f-44f7-b15f-67be05241204.yml"

  # Allow manual trigger
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CACHATAGENTSRV_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CACHATAGENTSRV_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CACHATAGENTSRV_AZURE_SUBSCRIPTION_ID }}

      - name: Log in to Azure Container Registry
        uses: docker/login-action@v2
        with:
          registry: portfolioacr01.azurecr.io
          username: ${{ secrets.CACHATAGENTSRV_REGISTRY_USERNAME }}
          password: ${{ secrets.CACHATAGENTSRV_REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./apps/backend/chatbot-service
          file: ./apps/backend/chatbot-service/Dockerfile
          push: true
          tags: portfolioacr01.azurecr.io/ca-chatagent-srv:${{ github.sha }},portfolioacr01.azurecr.io/ca-chatagent-srv:latest

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v2
        with:
          containerAppName: ca-chatagent-srv
          resourceGroup: rg-bankguru
          imageToDeploy: portfolioacr01.azurecr.io/ca-chatagent-srv:${{ github.sha }}
