# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - as-chat-srv

on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/main_as-chat-srv-srv.yml"
      - "apps/backend/chatbot-service/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: portfolioacr01.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_08FC317EC62645F497057DB7F8FA497D }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_1F8E98089F7D49ECB2BF75D2D3581343 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: ./apps/backend/chatbot-service
          push: true
          tags: portfolioacr01.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_08FC317EC62645F497057DB7F8FA497D }}/img-chatbot:${{ github.sha }}
          file: ./apps/backend/chatbot-service/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D93D27E9AE8D4889AFA646A9B9457C58 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_CDB0C577823943ECA2AE28224AF8F123 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D25E93F2598B48F890D68969BCFFF333 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: "as-chat-srv"
          slot-name: "Production"
          images: "portfolioacr01.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_08FC317EC62645F497057DB7F8FA497D }}/img-chatbot:${{ github.sha }}"
